db-uri = "postgres://authenticator:teste123@localhost:5432/teste"
db-schemas = "public"
db-anon-role = "anon"
jwt-secret = "segredo-de-teste-local-com-mais-de-32-caracteres!!"
server-port = 3000
db-extra-search-path = "public"
db-max-rows = 1000
