-- Listas suspensas (aba LISTAS SUSPENSAS da Tabela Principal BDG v16).
-- ativo = true  : valores oficiais, oferecidos no formulário.
-- ativo = false : valores que só aparecem no histórico; ficam registrados, mas o
--                 formulário não oferece. Revisar: padronizar ou promover a oficial.
-- Rodar depois de 01_esquema_roi.sql.
insert into dominio (campo, valor, ordem, ativo) values
  ('local', 'Interno', 1, true),
  ('local', 'Entorno', 2, true),
  ('local', 'Interno/Entorno', 3, true),
  ('local', 'Não Informado', 4, true),
  ('base_op', 'Sub Base Belo Horizonte', 1, true),
  ('base_op', 'Base Operacional de Curvelo', 2, true),
  ('base_op', 'Sub Base de Januária', 3, true),
  ('ufbio', 'Alto Médio São Francisco', 1, true),
  ('ufbio', 'Alto Paranaíba', 2, true),
  ('ufbio', 'Centro Norte', 3, true),
  ('ufbio', 'Centro Oeste', 4, true),
  ('ufbio', 'Centro Sul', 5, true),
  ('ufbio', 'Jequitinhonha', 6, true),
  ('ufbio', 'Mata', 7, true),
  ('ufbio', 'Metropolitano', 8, true),
  ('ufbio', 'Nordeste', 9, true),
  ('ufbio', 'Noroeste', 10, true),
  ('ufbio', 'Norte', 11, true),
  ('ufbio', 'Rio Doce', 12, true),
  ('ufbio', 'Sul', 13, true),
  ('ufbio', 'Triângulo', 14, true),
  ('categoria', 'APA', 1, true),
  ('categoria', 'APE', 2, true),
  ('categoria', 'ESEC', 3, true),
  ('categoria', 'FLOE', 4, true),
  ('categoria', 'MONA', 5, true),
  ('categoria', 'PAR', 6, true),
  ('categoria', 'RDS', 7, true),
  ('categoria', 'REBIO', 8, true),
  ('categoria', 'RVS', 9, true),
  ('nome_uc', 'Acauã', 1, true),
  ('nome_uc', 'Água Limpa', 2, true),
  ('nome_uc', 'Águas Vertentes', 3, true),
  ('nome_uc', 'Alto Cariri', 4, true),
  ('nome_uc', 'Alto Mucuri', 5, true),
  ('nome_uc', 'Arêdes', 6, true),
  ('nome_uc', 'Bacia Hidrográfica do Rio Machado', 7, true),
  ('nome_uc', 'Baleia', 8, true),
  ('nome_uc', 'Biribiri', 9, true),
  ('nome_uc', 'Botumirim', 10, true),
  ('nome_uc', 'Cachoeira das Andorinhas', 11, true),
  ('nome_uc', 'Caminho dos Gerais', 12, true),
  ('nome_uc', 'Campos Altos', 13, true),
  ('nome_uc', 'Cercadinho', 14, true),
  ('nome_uc', 'Cochá e Gibão', 15, true),
  ('nome_uc', 'Corumbá', 16, true),
  ('nome_uc', 'Fechos', 17, true),
  ('nome_uc', 'Fernão Dias', 18, true),
  ('nome_uc', 'Grão Mogol', 19, true),
  ('nome_uc', 'Gruta Rei do Mato', 20, true),
  ('nome_uc', 'Ibitipoca', 21, true),
  ('nome_uc', 'Itacolomi', 22, true),
  ('nome_uc', 'Itatiaia', 23, true),
  ('nome_uc', 'Lagedão', 24, true),
  ('nome_uc', 'Lagoa do Cajueiro', 25, true),
  ('nome_uc', 'Lapa Grande', 26, true),
  ('nome_uc', 'Lapa Nova de Vazante', 27, true),
  ('nome_uc', 'Libélulas da Serra de São José', 28, true),
  ('nome_uc', 'Macaúbas', 29, true),
  ('nome_uc', 'Mata de Krambeck', 30, true),
  ('nome_uc', 'Mata do Cedro', 31, true),
  ('nome_uc', 'Mata do Limoeiro', 32, true),
  ('nome_uc', 'Mata dos Ausentes', 33, true),
  ('nome_uc', 'Mata dos Muriquis', 34, true),
  ('nome_uc', 'Mata Seca', 35, true),
  ('nome_uc', 'Montezuma', 36, true),
  ('nome_uc', 'Nova Baden', 37, true),
  ('nome_uc', 'Pandeiros', 38, true),
  ('nome_uc', 'Paracatu', 39, true),
  ('nome_uc', 'Parque Cataguás', 40, true),
  ('nome_uc', 'Pau Furado', 41, true),
  ('nome_uc', 'Peter Lund', 42, true),
  ('nome_uc', 'Pico da Ibituruna', 43, true),
  ('nome_uc', 'Pico do Itambé', 44, true),
  ('nome_uc', 'Rio Corrente', 45, true),
  ('nome_uc', 'Rio Doce', 46, true),
  ('nome_uc', 'Rio Pandeiros', 47, true),
  ('nome_uc', 'Rio Preto', 48, true),
  ('nome_uc', 'Rios Tijuco e da Prata', 49, true),
  ('nome_uc', 'Sagarana', 50, true),
  ('nome_uc', 'Santa Izabel e Espalha', 51, true),
  ('nome_uc', 'São José', 52, true),
  ('nome_uc', 'Seminário Menor de Mariana', 53, true),
  ('nome_uc', 'Serra Azul', 54, true),
  ('nome_uc', 'Serra da Boa Esperança', 55, true),
  ('nome_uc', 'Serra da Candonga', 56, true),
  ('nome_uc', 'Serra da Moeda', 57, true),
  ('nome_uc', 'Serra da Piedade', 58, true),
  ('nome_uc', 'Serra das Araras', 59, true),
  ('nome_uc', 'Serra das Aroeiras', 60, true),
  ('nome_uc', 'Serra do Brigadeiro', 61, true),
  ('nome_uc', 'Serra do Cabral', 62, true),
  ('nome_uc', 'Serra do Intendente', 63, true),
  ('nome_uc', 'Serra do Ouro Branco', 64, true),
  ('nome_uc', 'Serra do Papagaio', 65, true),
  ('nome_uc', 'Serra do Rola Moça', 66, true),
  ('nome_uc', 'Serra do Sabonetal', 67, true),
  ('nome_uc', 'Serra do Sobrado', 68, true),
  ('nome_uc', 'Serra Negra', 69, true),
  ('nome_uc', 'Serra Negra da Mantiqueira', 70, true),
  ('nome_uc', 'Serra Nova', 71, true),
  ('nome_uc', 'Serra Verde', 72, true),
  ('nome_uc', 'Sete Salões', 73, true),
  ('nome_uc', 'Sul RMBH', 74, true),
  ('nome_uc', 'Sumidouro', 75, true),
  ('nome_uc', 'Todos os Santos', 76, true),
  ('nome_uc', 'Tripuí', 77, true),
  ('nome_uc', 'Uaimií', 78, true),
  ('nome_uc', 'Vargem da Pedra', 79, true),
  ('nome_uc', 'Vargem das Flores', 80, true),
  ('nome_uc', 'Várzea do Lageado e Serra do Raio', 81, true),
  ('nome_uc', 'Verde Grande', 82, true),
  ('nome_uc', 'Veredas do Acari', 83, true),
  ('nome_uc', 'Veredas do Peruaçu', 84, true),
  ('nome_uc', 'Jaíba', 85, true),
  ('nome_uc', 'Várzea da Lapa', 999, false),
  ('grupo', 'Proteção Integral', 1, true),
  ('grupo', 'Uso Sustentável', 2, true),
  ('municipio', 'Açucena', 1, true),
  ('municipio', 'Aiuruoca', 2, true),
  ('municipio', 'Aiuruoca/Baependi', 3, true),
  ('municipio', 'Alagoa', 4, true),
  ('municipio', 'Alagoa/Baependi', 5, true),
  ('municipio', 'Alfenas', 6, true),
  ('municipio', 'Araguari', 7, true),
  ('municipio', 'Araponga', 8, true),
  ('municipio', 'Arcos', 9, true),
  ('municipio', 'Arinos', 10, true),
  ('municipio', 'Augusto de Lima', 11, true),
  ('municipio', 'Baependi', 12, true),
  ('municipio', 'Belo Horizonte', 13, true),
  ('municipio', 'Belo Horizonte/Nova Lima', 14, true),
  ('municipio', 'Belo Horizonte/Vespasiano', 15, true),
  ('municipio', 'Betim', 16, true),
  ('municipio', 'Betim/Contagem', 17, true),
  ('municipio', 'Boa Esperança', 18, true),
  ('municipio', 'Boa Esperança/IIicínea', 19, true),
  ('municipio', 'Bom Jesus do Galho', 20, true),
  ('municipio', 'Bonito de Minas', 21, true),
  ('municipio', 'Bonito de Minas/Januária', 22, true),
  ('municipio', 'Botumirim', 23, true),
  ('municipio', 'Brazópolis', 24, true),
  ('municipio', 'Brumadinho', 25, true),
  ('municipio', 'Buenópolis', 26, true),
  ('municipio', 'Buenópolis/Joaquim Felício', 27, true),
  ('municipio', 'Caeté', 28, true),
  ('municipio', 'Caldas/Santa Rita de Caldas', 29, true),
  ('municipio', 'Camanducaia', 30, true),
  ('municipio', 'Cambuquira/Campanha', 31, true),
  ('municipio', 'Campos Altos', 32, true),
  ('municipio', 'Canaã', 33, true),
  ('municipio', 'Caraí', 34, true),
  ('municipio', 'Carmópolis de Minas', 35, true),
  ('municipio', 'Cataguases', 36, true),
  ('municipio', 'Catas Altas', 37, true),
  ('municipio', 'Catuji', 38, true),
  ('municipio', 'Cel.Xavier Chaves/iradentes', 39, true),
  ('municipio', 'Chapada do Norte', 40, true),
  ('municipio', 'Chapada Gaúcha', 41, true),
  ('municipio', 'Cláudio', 42, true),
  ('municipio', 'Conceição do Mato Dentro', 43, true),
  ('municipio', 'Conceição do Mato Dentro/Congonhas do Norte', 44, true),
  ('municipio', 'Conceição do Mato Dentro/Santana do Riacho', 45, true),
  ('municipio', 'Cônego Marinho', 46, true),
  ('municipio', 'Confins', 47, true),
  ('municipio', 'Congonhas do Norte', 48, true),
  ('municipio', 'Conselheiro Pena', 49, true),
  ('municipio', 'Contagem', 50, true),
  ('municipio', 'Cordisburgo', 51, true),
  ('municipio', 'Coronel Xavier Chaves', 52, true),
  ('municipio', 'Córrego Danta', 53, true),
  ('municipio', 'Couto de Magalhães de Minas', 54, true),
  ('municipio', 'Diamantina', 55, true),
  ('municipio', 'Dionisio', 56, true),
  ('municipio', 'Dionísio', 57, true),
  ('municipio', 'Divino', 58, true),
  ('municipio', 'Ervália', 59, true),
  ('municipio', 'Ervália/Araponga', 60, true),
  ('municipio', 'Espinosa', 61, true),
  ('municipio', 'Espírito Santo Dourado', 62, true),
  ('municipio', 'Espirito Santo Dourado/puiuna', 63, true),
  ('municipio', 'Extrema', 64, true),
  ('municipio', 'Fama', 65, true),
  ('municipio', 'Felício dos Santos', 66, true),
  ('municipio', 'Fervedouro', 67, true),
  ('municipio', 'Gameleiras', 68, true),
  ('municipio', 'Gonçalves', 69, true),
  ('municipio', 'Governador Valadares', 70, true),
  ('municipio', 'Grão Mogol', 71, true),
  ('municipio', 'Guanhães', 72, true),
  ('municipio', 'Guapé', 73, true),
  ('municipio', 'Ibirité', 74, true),
  ('municipio', 'Ilicínea', 75, true),
  ('municipio', 'Ilicínea/Guapé', 76, true),
  ('municipio', 'Ipoema', 77, true),
  ('municipio', 'Ipuiúna', 78, true),
  ('municipio', 'Ipuiúna/Espírito Santo do Dourado', 79, true),
  ('municipio', 'Ipuiúna/Poço Fundo', 80, true),
  ('municipio', 'Itabira', 81, true),
  ('municipio', 'Itabirito', 82, true),
  ('municipio', 'Itabirito/Nova Lima', 83, true),
  ('municipio', 'Itabirto/Moeda', 84, true),
  ('municipio', 'Itacarambi', 85, true),
  ('municipio', 'Itaipé', 86, true),
  ('municipio', 'Itamarandiba', 87, true),
  ('municipio', 'Itamonte', 88, true),
  ('municipio', 'Itapeva', 89, true),
  ('municipio', 'Ituiutaba', 90, true),
  ('municipio', 'Jaíba', 91, true),
  ('municipio', 'Januária', 92, true),
  ('municipio', 'Joaquim Felício', 93, true),
  ('municipio', 'Juiz de Fora', 94, true),
  ('municipio', 'Ladainha', 95, true),
  ('municipio', 'Lagoa Santa', 96, true),
  ('municipio', 'Lambari', 97, true),
  ('municipio', 'Leme do Prado', 98, true),
  ('municipio', 'Leme do Prado/Turmalina', 99, true),
  ('municipio', 'Lima Duarte', 100, true),
  ('municipio', 'Machado', 101, true),
  ('municipio', 'Malacacheta', 102, true),
  ('municipio', 'Mamonas', 103, true),
  ('municipio', 'Manga', 104, true),
  ('municipio', 'Mariana', 105, true),
  ('municipio', 'Mário Campos/Brumadinho', 106, true),
  ('municipio', 'Marliéria', 107, true),
  ('municipio', 'Matias Cardoso', 108, true),
  ('municipio', 'Mato Verde', 109, true),
  ('municipio', 'Miradouro', 110, true),
  ('municipio', 'Moeda', 111, true),
  ('municipio', 'Moeda/Itabirito', 112, true),
  ('municipio', 'Monte Azul', 113, true),
  ('municipio', 'Montes Claros', 114, true),
  ('municipio', 'Montezuma', 115, true),
  ('municipio', 'Morro do Pilar', 116, true),
  ('municipio', 'Muriaé', 117, true),
  ('municipio', 'Nova Lima', 118, true),
  ('municipio', 'Novo Cruzeiro', 119, true),
  ('municipio', 'Olaria', 120, true),
  ('municipio', 'Ouro Branco', 121, true),
  ('municipio', 'Ouro Branco/Ouro Preto', 122, true),
  ('municipio', 'Ouro Preto', 123, true),
  ('municipio', 'Ouro Preto/Mariana', 124, true),
  ('municipio', 'Paracatu', 125, true),
  ('municipio', 'Paraguaçu', 126, true),
  ('municipio', 'Paraisópolis', 127, true),
  ('municipio', 'Pedra Bonita', 128, true),
  ('municipio', 'Pedra de Maria da Cruz', 129, true),
  ('municipio', 'Pedro Leopoldo', 130, true),
  ('municipio', 'Pedro Leopoldo/Lagoa Santa', 131, true),
  ('municipio', 'Poço Fundo', 132, true),
  ('municipio', 'Poço Fundo/São João da Mata', 133, true),
  ('municipio', 'Porteirinha', 134, true),
  ('municipio', 'Poté', 135, true),
  ('municipio', 'Pouso Alto', 136, true),
  ('municipio', 'Prados', 137, true),
  ('municipio', 'Resplendor', 138, true),
  ('municipio', 'Riachinho', 139, true),
  ('municipio', 'Riachinho/Arinos', 140, true),
  ('municipio', 'Rio Acima', 141, true),
  ('municipio', 'Rio Pardo de Minas', 142, true),
  ('municipio', 'Rio Vermelho', 143, true),
  ('municipio', 'Sabará', 144, true),
  ('municipio', 'Salto da Divisa', 145, true),
  ('municipio', 'Santa Bárbara', 146, true),
  ('municipio', 'Santa Cruz de Minas', 147, true),
  ('municipio', 'Santa Luzia', 148, true),
  ('municipio', 'Santa Maria do Salto', 149, true),
  ('municipio', 'Santa Maria do Salto/Guaratinga', 150, true),
  ('municipio', 'Santa Rita do Ituêto', 151, true),
  ('municipio', 'Santana do Riacho', 152, true),
  ('municipio', 'Santana do Riacho/Conceição do Mato Dentro', 153, true),
  ('municipio', 'Santana do Riacho/Congonhas do Norte', 154, true),
  ('municipio', 'Santo Antônio do Itambé', 155, true),
  ('municipio', 'São Bartolomeu/Ouro Preto', 156, true),
  ('municipio', 'São Gonçalo do Rio Preto', 157, true),
  ('municipio', 'São Gonçalo do Rio Preto/Couto de Mag. de Minas/Felício dos Santos', 158, true),
  ('municipio', 'São João Del Rei', 159, true),
  ('municipio', 'São José da Lapa', 160, true),
  ('municipio', 'São José da Lapa/Pedro Leopoldo', 161, true),
  ('municipio', 'Sapucaí-Mirim', 162, true),
  ('municipio', 'Senador Modestino Gonçalves', 163, true),
  ('municipio', 'Sericita', 164, true),
  ('municipio', 'Serra Azul de Minas', 165, true),
  ('municipio', 'Serranópolis de Minas', 166, true),
  ('municipio', 'Serro', 167, true),
  ('municipio', 'Sete Lagoas', 168, true),
  ('municipio', 'Taipé', 169, true),
  ('municipio', 'Teófilo Otoni', 170, true),
  ('municipio', 'Timóteo', 171, true),
  ('municipio', 'Tiradentes', 172, true),
  ('municipio', 'Toledo', 173, true),
  ('municipio', 'Uberlândia', 174, true),
  ('municipio', 'Vazante', 175, true),
  ('municipio', 'Vespasiano', 176, true),
  ('municipio', 'Congonhal', 177, true),
  ('municipio', 'Outros', 178, true),
  ('municipio', 'Baependi/Itamonte', 179, true),
  ('municipio', 'Bias Fortes', 180, true),
  ('municipio', 'Pouso Alto/Itamonte', 181, true),
  ('municipio', 'Alagoa/Aiuruoca', 182, true),
  ('municipio', 'Santa Rita do Ibitipoca', 183, true),
  ('municipio', 'Riacho dos Machados', 184, true),
  ('municipio', 'Espirito Santo Dourado/Ipuiuna', 185, true),
  ('municipio', 'Cel.Xavier Chaves/Tiradentes', 186, true),
  ('municipio', 'Mário Campos', 187, true),
  ('municipio', 'Bom Jesus do galho', 999, false),
  ('municipio', 'Ipuiúna, Espírito Santo do Dourado', 999, false),
  ('municipio', 'Itabirito/Moeda', 999, false),
  ('municipio', 'Itaipé/Catuji', 999, false),
  ('municipio', 'Itambacuri', 999, false),
  ('municipio', 'Jaguaraçu', 999, false),
  ('municipio', 'Matias Cardoso e Jaíba', 999, false),
  ('municipio', 'Santa Bárbara do Monte Verde', 999, false),
  ('municipio', 'Santa Maria do Salto/ Guaratinga', 999, false),
  ('municipio', 'Santa Rita do Itueto', 999, false),
  ('municipio', 'Santana do Garambéu', 999, false),
  ('municipio', 'São João del Rei', 999, false),
  ('municipio', 'Urucuia', 999, false),
  ('municipio', 'serro', 999, false),
  ('bioma_uc', 'Caatinga', 1, true),
  ('bioma_uc', 'Caatinga/Cerrado', 2, true),
  ('bioma_uc', 'Cerrado', 3, true),
  ('bioma_uc', 'Cerrado/Mata Atlântica', 4, true),
  ('bioma_uc', 'Mata Atlântica', 5, true),
  ('f_detec', 'Bombeiro Militar CBMMG', 1, true),
  ('f_detec', 'Brigadista Parceiro', 2, true),
  ('f_detec', 'Brigadista Prefeitura', 3, true),
  ('f_detec', 'Brigadista Previncêndio', 4, true),
  ('f_detec', 'Brigadista SAFEMED', 5, true),
  ('f_detec', 'Brigadista Voluntário', 6, true),
  ('f_detec', 'Defesa Civil Municipal', 7, true),
  ('f_detec', 'Denúncia (Ação Olho no Fogo Alphaville)', 8, true),
  ('f_detec', 'Denúncia 0800 FTP', 9, true),
  ('f_detec', 'Denúncia Anônima', 10, true),
  ('f_detec', 'Denúncia de Usuário da BR040', 11, true),
  ('f_detec', 'Denúncia Sub Base Januária', 12, true),
  ('f_detec', 'Diretor DPIFE/Previncêndio', 13, true),
  ('f_detec', 'Funcionário COPASA', 14, true),
  ('f_detec', 'Funcionário da Prefeitura de Conceição do Mato Dentro', 15, true),
  ('f_detec', 'Funcionário da Preveitura Mun. Resplendor', 16, true),
  ('f_detec', 'Funcionário da UC', 17, true),
  ('f_detec', 'Funcionário da UC - Monitoramento por Vídeo Vigilância', 18, true),
  ('f_detec', 'Funcionário da UC - Torre 1 e 2 do P.E Lagoa do Cajueiro', 19, true),
  ('f_detec', 'Funcionário da UC - Torre de Observação', 20, true),
  ('f_detec', 'Funcionário da UC - Torre de Observação do Pântano', 21, true),
  ('f_detec', 'Funcionário da UC - Torre de Observação do PEMS', 22, true),
  ('f_detec', 'Funcionário de Fazenda', 23, true),
  ('f_detec', 'Funcionário do MNE Itatiaia', 24, true),
  ('f_detec', 'Funcionário do MNE Várzea do Lageado', 25, true),
  ('f_detec', 'Funcionário do PE Pico do Itambé', 26, true),
  ('f_detec', 'Funcionário do PE Serra do Ouro Branco', 27, true),
  ('f_detec', 'Funcionário ICMBIO', 28, true),
  ('f_detec', 'Funcionário IEF', 29, true),
  ('f_detec', 'Funcionário Outra UC', 30, true),
  ('f_detec', 'Funcionário Parceiro', 31, true),
  ('f_detec', 'Funcionario Prefeitura', 32, true),
  ('f_detec', 'Funcionário Prefeitura (Secretário Municipal)', 33, true),
  ('f_detec', 'Funcionario Semad', 34, true),
  ('f_detec', 'Funcionário UC PESRM', 35, true),
  ('f_detec', 'Funcionarios Parceiros EPAMIG', 36, true),
  ('f_detec', 'Gerente da UC', 37, true),
  ('f_detec', 'Gerente do MNE Varzea da Palma', 38, true),
  ('f_detec', 'Gerente do Parque Serra do Sobrado', 39, true),
  ('f_detec', 'Gerente do PEVP', 40, true),
  ('f_detec', 'Gerente do Previncêndio', 41, true),
  ('f_detec', 'Gerente Outra UC', 42, true),
  ('f_detec', 'Gerente Parque Serra do Cural', 43, true),
  ('f_detec', 'Líder de Brigada Previncêndio', 44, true),
  ('f_detec', 'Monitoramento Aéreo', 45, true),
  ('f_detec', 'Monitoramento Aéreo (por Air Tractor)', 46, true),
  ('f_detec', 'Monitoramento Aéreo (por Helicóptero)', 47, true),
  ('f_detec', 'Morador da UC', 48, true),
  ('f_detec', 'Morador do Entorno', 49, true),
  ('f_detec', 'Não Informado', 50, true),
  ('f_detec', 'Outros/Gerente de RPPN', 51, true),
  ('f_detec', 'Polícia Militar PMMG', 52, true),
  ('f_detec', 'Satélite de Monitoramento', 53, true),
  ('f_detec', 'Visitante da UC', 54, true),
  ('f_detec', 'Denúncia - Aplicativo de Mensagem', 55, true),
  ('f_detec', 'Coordenador de Brigadas do PARNA Gandarela', 56, true),
  ('f_detec', 'Outros: Coordenador do Santuário do Caraça', 57, true),
  ('f_detec', 'Funcionário da APAEAV', 58, true),
  ('f_detec', 'Outros', 59, true),
  ('f_detec', 'Funcionários do Retiro das Pedras', 60, true),
  ('f_detec', 'Funcionario da Prefeitura de Santa Cruz de Minas', 61, true),
  ('f_detec', 'Funcionário de Empresa', 62, true),
  ('f_detec', 'Militar do Exército', 63, true),
  ('f_detec', 'Brigadista Compensação Minerária', 64, true),
  ('f_detec', 'Funcionário do Hospital da Baleia', 65, true),
  ('f_detec', 'Brigadista Parceiro - Morador do Entorno', 999, false),
  ('f_detec', 'Coordenador da Defesa Civil Municipal', 999, false),
  ('f_detec', 'Defesa Civil Baependi', 999, false),
  ('f_detec', 'Funcionário - RPPN Caraça', 999, false),
  ('f_detec', 'Funcionário COPASA - Video Vigilância', 999, false),
  ('f_detec', 'Funcionário PQ Verde Grande', 999, false),
  ('f_detec', 'Funcionário Prefeitura', 999, false),
  ('f_detec', 'Funcionário do Condominio Nosso Rancho', 999, false),
  ('f_detec', 'Funcionários da RPPN Santo Ângelo', 999, false),
  ('f_detec', 'Gerente RPPN', 999, false),
  ('f_detec', 'Gerente do PNM do Tabuleiro', 999, false),
  ('f_detec', 'Ligação nos Bombeiros', 999, false),
  ('f_detec', 'Ligação telefônica (193)', 999, false),
  ('f_detec', 'Morador da UC - Proprietário de Fazenda', 999, false),
  ('f_detec', 'Proprietário de Fazenda', 999, false),
  ('f_detec', 'Transeunte', 999, false),
  ('f_detec', 'Turista', 999, false),
  ('f_detec', 'Vigia do PM Mangabeiras', 999, false),
  ('f_detec', 'Vigia do posto 10', 999, false),
  ('causa_p', 'Ação Antrópica - Atividade de Vazanteiros', 1, true),
  ('causa_p', 'Ação Antrópica - Eliminação de Carrapatos', 2, true),
  ('causa_p', 'Ação Antrópica - Incendiário/Piromaníaco', 3, true),
  ('causa_p', 'Ação Antrópica - Incêndio para Invasão de terras', 4, true),
  ('causa_p', 'Ação Antrópica - Não Especificada', 5, true),
  ('causa_p', 'Ação Antrópica - Pesca', 6, true),
  ('causa_p', 'Ação Antrópica - Provocada por Usuários de Drogas', 7, true),
  ('causa_p', 'Ação Antrópica - Queima para Eliminar Animais Peçonhentos', 8, true),
  ('causa_p', 'Ação Antrópica - Transeuntes', 9, true),
  ('causa_p', 'Ação Antrópica - Veículo em Chamas', 10, true),
  ('causa_p', 'Acidental', 11, true),
  ('causa_p', 'Cabo de Alta Tensão', 12, true),
  ('causa_p', 'Caça', 13, true),
  ('causa_p', 'Coleta de Sempre Vivas', 14, true),
  ('causa_p', 'Desconhecida', 15, true),
  ('causa_p', 'Eliminação de Animais Peçonheintos/Insetos', 16, true),
  ('causa_p', 'Extração de Espécie Vegetal', 17, true),
  ('causa_p', 'Extração de Madeira', 18, true),
  ('causa_p', 'Extração de Mel de Abelha', 19, true),
  ('causa_p', 'Extração Mineral', 20, true),
  ('causa_p', 'Fagulha de Máquinas', 21, true),
  ('causa_p', 'Fagulha de um outro foco de incêndio nas proximidades', 22, true),
  ('causa_p', 'Fogos de Artifício', 23, true),
  ('causa_p', 'Fogueira de Acampamento', 24, true),
  ('causa_p', 'Forno de Carvão', 25, true),
  ('causa_p', 'Limpeza de Área para construção civil', 26, true),
  ('causa_p', 'Limpeza de Área para Cultivo', 27, true),
  ('causa_p', 'Limpeza de Área para Expansão Urbana', 28, true),
  ('causa_p', 'Limpeza de Área para Fins Agropecuários - Não especificados', 29, true),
  ('causa_p', 'Limpeza de Área para uso alternativo do solo', 30, true),
  ('causa_p', 'Limpeza de Área Urbana', 31, true),
  ('causa_p', 'Limpeza de Estrada', 32, true),
  ('causa_p', 'Limpeza de Estradas/Rodovias/Ferrovias', 33, true),
  ('causa_p', 'Limpeza de Lote', 34, true),
  ('causa_p', 'Limpeza de sub bosque de eucaliptal', 35, true),
  ('causa_p', 'Limpeza de Trilha', 36, true),
  ('causa_p', 'Litígio com o IEF-MG', 37, true),
  ('causa_p', 'Mineração', 38, true),
  ('causa_p', 'Não Informada', 39, true),
  ('causa_p', 'Natural (incêndio causado por queda de raio)', 40, true),
  ('causa_p', 'Outro: Acidente Veículo', 41, true),
  ('causa_p', 'Outro: conflitos com brigadistas parceiros', 42, true),
  ('causa_p', 'Outro: Criminoso', 43, true),
  ('causa_p', 'Outro: Demarcação de Via Urbana', 44, true),
  ('causa_p', 'Outro: Exploração Minerária', 45, true),
  ('causa_p', 'Outro: Exploração Minerária e Silvicultura', 46, true),
  ('causa_p', 'Outro: Exploração Minerária e Silvicultura com fornos de carvão.', 47, true),
  ('causa_p', 'Outro: Guimba de Cigarro', 48, true),
  ('causa_p', 'Outro: Loteamento irregular', 49, true),
  ('causa_p', 'Outro: Motocross', 50, true),
  ('causa_p', 'Outro: Pane bomba elétrica', 51, true),
  ('causa_p', 'Outro: Queima de Botafora Rural', 52, true),
  ('causa_p', 'Outro: Queima de cabos de guatambu', 53, true),
  ('causa_p', 'Possivel vingança entre entes familiares', 54, true),
  ('causa_p', 'Queima de Área para Cultivo de Eucalipto', 55, true),
  ('causa_p', 'Queima de Lixo', 56, true),
  ('causa_p', 'Queima de Resíduos de Exploração Vegetal', 57, true),
  ('causa_p', 'Queima de vegetação para realização de Pesca Ilegal', 58, true),
  ('causa_p', 'Queima de vegetaçãoo para limpeza de quintal', 59, true),
  ('causa_p', 'Queima para Coleta de Sempre Vivas', 60, true),
  ('causa_p', 'Reignição', 61, true),
  ('causa_p', 'Renovação de Pastagem Natural', 62, true),
  ('causa_p', 'Renovação de Pastagem Plantada', 63, true),
  ('causa_p', 'Represália de Proprietários vizinhos', 64, true),
  ('causa_p', 'Restos de Cigarro', 65, true),
  ('causa_p', 'Retaliação em detrimento de processo de fiscalização', 66, true),
  ('causa_p', 'Retirada de Vegetação Nativa', 67, true),
  ('causa_p', 'Ritual Religioso', 68, true),
  ('causa_p', 'Supressão de Vegetação para Limpeza de Área', 69, true),
  ('causa_p', 'Transeuntes', 70, true),
  ('causa_p', 'Vandalismo', 71, true),
  ('causa_p', 'Visitantes da UC', 72, true),
  ('causa_p', 'Abertura/Limpeza de área para loteamento', 999, false),
  ('causa_p', 'Ação Antrópica - Derretimento de Fio de Cobre', 999, false),
  ('causa_p', 'Ação Antrópica - Queima de Caixa de Marimbondo', 999, false),
  ('causa_p', 'Ação Antrópica - Queima de fios de cobre furtados', 999, false),
  ('causa_p', 'Ação Antrópica - Queima para Eliminar Insetos', 999, false),
  ('causa_p', 'Ação antrópica - Queima para Eliminar Animais Peçonhentos', 999, false),
  ('causa_p', 'Conflito Fundiário', 999, false),
  ('causa_p', 'Disputa Territorial', 999, false),
  ('causa_p', 'Extração de Mel', 999, false),
  ('causa_p', 'Fogos de artifício', 999, false),
  ('causa_p', 'Incidente ao realizar MIF', 999, false),
  ('causa_p', 'Limpeza de aceiro', 999, false),
  ('causa_p', 'Limpeza de estradas / rodovias / ferrovias', 999, false),
  ('causa_p', 'Limpeza de área para construção', 999, false),
  ('causa_p', 'Limpeza de área para cultivo', 999, false),
  ('causa_p', 'Limpeza de área para loteamento', 999, false),
  ('causa_p', 'Litígio com a administração municipal', 999, false),
  ('causa_p', 'Litígio com o IEF/Unidade de Conservação', 999, false),
  ('causa_p', 'Outro: Abertura de Estrada', 999, false),
  ('causa_p', 'Outro: Curto circuito nos fios de uma caixa D''água', 999, false),
  ('causa_p', 'Outro: Interesse Imobiliário', 999, false),
  ('causa_p', 'Outro: Manejo irregular de abelhas', 999, false),
  ('causa_p', 'Outro: Retirada Irregular de Pedras', 999, false),
  ('causa_p', 'Queda de Balão', 999, false),
  ('causa_p', 'Queima Não Autorizada de Espécie Exótica', 999, false),
  ('causa_p', 'Queima Prescrita', 999, false),
  ('causa_p', 'Queima de Canavial', 999, false),
  ('causa_p', 'Queima de Restos de Exploração', 999, false),
  ('causa_p', 'Queima de vegetação para limpeza de quintal', 999, false),
  ('causa_p', 'Queima para fins imobiliários', 999, false),
  ('causa_p', 'Renovação de pastagem natural', 999, false),
  ('causa_p', 'Retirada de Pedras (Laje)', 999, false),
  ('causa_p', 'Ritual religioso', 999, false),
  ('causa_p', 'limpeza do acesso a linha férrea para recolhimento de carga de milho roubada da Empresa VLI.', 999, false),
  ('ag_causal', 'Arrendatário', 1, true),
  ('ag_causal', 'Assentado', 2, true),
  ('ag_causal', 'Suspeitos em Fuga', 3, true),
  ('ag_causal', 'Caçador', 4, true),
  ('ag_causal', 'Caçador/Pescador', 5, true),
  ('ag_causal', 'Carvoeiro', 6, true),
  ('ag_causal', 'Criador de Animais', 7, true),
  ('ag_causal', 'Criador de Cavalo', 8, true),
  ('ag_causal', 'Criador de Gado', 9, true),
  ('ag_causal', 'Descarga Elétrica (raio)', 10, true),
  ('ag_causal', 'Descarga Eletrica (rede de alta tensão)', 11, true),
  ('ag_causal', 'Empresa Florestal', 12, true),
  ('ag_causal', 'Extrativista Vegetal', 13, true),
  ('ag_causal', 'Festeiro (uso de fogos de artifício)', 14, true),
  ('ag_causal', 'Funcionário de Empresa Responsável por Rodovia', 15, true),
  ('ag_causal', 'Funcionarios terceirizados da PBH', 16, true),
  ('ag_causal', 'Garimpeiro', 17, true),
  ('ag_causal', 'Incendiário/Piromaníaco', 18, true),
  ('ag_causal', 'Indeterminado', 19, true),
  ('ag_causal', 'Indígena', 20, true),
  ('ag_causal', 'Invasor', 21, true),
  ('ag_causal', 'Madeireiro', 22, true),
  ('ag_causal', 'Morador da UC', 23, true),
  ('ag_causal', 'Morador do Entorno', 24, true),
  ('ag_causal', 'Motorista/Operador de Máquina', 25, true),
  ('ag_causal', 'Não Informado', 26, true),
  ('ag_causal', 'Operador de Máquinas', 27, true),
  ('ag_causal', 'Outros: Motocross', 28, true),
  ('ag_causal', 'Pescador', 29, true),
  ('ag_causal', 'Posseiro', 30, true),
  ('ag_causal', 'Proprietário de Fazenda', 31, true),
  ('ag_causal', 'Proprietário ou Funcionário de Fazenda', 32, true),
  ('ag_causal', 'Religioso', 33, true),
  ('ag_causal', 'Transeunte', 34, true),
  ('ag_causal', 'Turista', 35, true),
  ('ag_causal', 'Vazanteiros', 36, true),
  ('ag_causal', 'Veículo em chamas', 37, true),
  ('ag_causal', 'Visitante da UC - Banhista', 38, true),
  ('ag_causal', 'Acidental', 999, false),
  ('ag_causal', 'Apicultor', 999, false),
  ('ag_causal', 'Ação Antrópica - Incendiário/Piromaníaco', 999, false),
  ('ag_causal', 'Brigadista', 999, false),
  ('ag_causal', 'Cabo de Alta Tensão', 999, false),
  ('ag_causal', 'Criador de gado', 999, false),
  ('ag_causal', 'Descarga Elétrica (rede de alta tensão)', 999, false),
  ('ag_causal', 'Explosão de automóvel', 999, false),
  ('ag_causal', 'Funcionário de "Lixão"', 999, false),
  ('ag_causal', 'Funcionário de Empresa Vizinha', 999, false),
  ('ag_causal', 'Funcionários terceirizados da PBH', 999, false),
  ('ag_causal', 'Não Informada', 999, false),
  ('ag_causal', 'Não informado', 999, false),
  ('ag_causal', 'Outros', 999, false),
  ('ag_causal', 'Outros: Ação Antrópica', 999, false),
  ('ag_causal', 'Outros: Evento Comemorativo/Show Pirotécnico', 999, false),
  ('ag_causal', 'Possível ação de crime conforme relato', 999, false),
  ('ag_causal', 'Renovação de Pastagem Plantada', 999, false),
  ('ag_causal', 'Transeuntes', 999, false),
  ('ag_causal', 'Área com indício de retirada de pedras', 999, false),
  ('ind_aut', 'Sim', 1, true),
  ('ind_aut', 'Não', 2, true)
on conflict do nothing;
